version: '3.8'

services:
  app:
    build:
      context: ./
      target: dev
    ports:
      - 3000:3000
    tty: true
    volumes:
      - ./:/app:cached
      - /app/node_modules
    restart: always